apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shop

labels:
  - pairs:
      app.kubernetes.io/part-of: shop

resources:
  - namespace.yaml
  - redis.yaml
  - api.yaml
  - worker.yaml
  - frontend.yaml

configMapGenerator:
  - name: shop-config
    literals:
      - APP_ENV=dev
      - LOG_LEVEL=INFO
      - API_URL=http://api:8000
      - API_TIMEOUT_SECONDS=2
      - WORK_MS=200

images:
  - name: shop
    newName: ghcr.io/pranshu-raj/shop
    newTag: dev
